apiVersion: v1
kind: Secret
metadata:
  name: cockroach-db
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-cockroach-db.git
  sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACBtjMYlu3xWyRPxhc25ofGTElv85escnxUxtkaBVss3oQAAAKibum8Im7pv
      CAAAAAtzc2gtZWQyNTUxOQAAACBtjMYlu3xWyRPxhc25ofGTElv85escnxUxtkaBVss3oQ
      AAAECJLHctH/qe0gOnM6uOK+Myf/xeo/v8eaFSC68bHSMyCW2MxiW7fFbJE/GFzbmh8ZMS
      W/zl6xyfFTG2RoFWyzehAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
      QFBgc=
      -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cockroach-db
  namespace: argocd
spec:
  description: Project for cockroach-db app
  sourceRepos:
    - '*'
  destinations:
    - namespace: cockroach-db
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroach-db
  namespace: argocd
spec:
  project: cockroach-db
  source:
    repoURL: git@github.com:dotcomrow/k8s-cockroach-db.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cockroach-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true