apiVersion: v1
kind: Secret
metadata:
  name: logging-and-monitoring
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/grafana-alloy-monitoring.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBa1Z9NZUfGvAdkC0qseEmQOcFSIT39DSFCF3NfmQFtGQAAAKhmve5VZr3u
    VQAAAAtzc2gtZWQyNTUxOQAAACBa1Z9NZUfGvAdkC0qseEmQOcFSIT39DSFCF3NfmQFtGQ
    AAAECM0Dc957fOw646YFfDWzg7rPolgd4ZlKzZxsR5Hlx1NFrVn01lR8a8B2QLSqx4SZA5
    wVIhPf0NIUIXc1+ZAW0ZAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: logging-and-monitoring
  namespace: argocd
spec:
  description: Project for logging and monitoring app
  sourceRepos:
    - '*'
  sourceNamespaces:
    - argocd
  destinations:
    - namespace: logging-and-monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: openobserve
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-and-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/config-management-plugin: avp-v1
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: logging-and-monitoring
  source:
    repoURL: git@github.com:dotcomrow/grafana-alloy-monitoring.git
    targetRevision: prod
    path: manifests
    plugin:
      name: avp-v1
  destination:
    server: https://kubernetes.default.svc
    namespace: logging-and-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m