apiVersion: v1
kind: Secret
metadata:
  name: mcp
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-mcp.git
  sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACB4tfMQkpoo5YryccL0E0n6T677n0Wu7AVx4N4zcXDOagAAAKgH8HpCB/B6
      QgAAAAtzc2gtZWQyNTUxOQAAACB4tfMQkpoo5YryccL0E0n6T677n0Wu7AVx4N4zcXDOag
      AAAEBoUY5Qb9TQbCcxs7dSRNY4uHSDfq7zvwc09jaY8HCptHi18xCSmijlivJxwvQTSfpP
      rvufRa7sBXHg3jNxcM5qAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
      QFBgc=
      -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mcp
  namespace: argocd
spec:
  description: Project for mcp app
  sourceRepos:
    - '*'
  destinations:
    - namespace: mcp
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp
  namespace: argocd
spec:
  project: mcp
  source:
    repoURL: git@github.com:dotcomrow/k8s-mcp.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true