apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-teleport
  namespace: argocd
spec:
  description: Project for k8s-teleport
  sourceRepos:
    - '*'
  destinations:
    - namespace: teleport
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-teleport
  namespace: argocd
  annotations:
    argocd.argoproj.io/config-management-plugin: avp-v1
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: k8s-teleport
  source:
    repoURL: https://github.com/dotcomrow/k8s-teleport.git
    targetRevision: prod
    path: manifests
    plugin:
      name: avp-v1
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: apps
      kind: DaemonSet
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: batch
      kind: Job
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: batch
      kind: CronJob
      jqPathExpressions:
        - .spec.jobTemplate.spec.template.spec.containers[].resources
        - .spec.jobTemplate.spec.template.spec.initContainers[].resources

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m