apiVersion: v1
kind: Secret
metadata:
  name: rules-engine
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-rules-engine.git
  sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACCVnbkK9GhWEEAo2DntVk+peIPzqmYDgyo20Y6NJDSLiwAAAKg57ZC6Oe2Q
      ugAAAAtzc2gtZWQyNTUxOQAAACCVnbkK9GhWEEAo2DntVk+peIPzqmYDgyo20Y6NJDSLiw
      AAAEC0d584c7F9kUaUJm6+7JIHsjb+jSVOC4Ab7nbwWVXqUZWduQr0aFYQQCjYOe1WT6l4
      g/OqZgODKjbRjo0kNIuLAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
      QFBgc=
      -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rules-engine
  namespace: argocd
spec:
  description: Project for rules-engine app
  sourceRepos:
    - '*'
  destinations:
    - namespace: drools
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rules-engine
  namespace: argocd
spec:
  project: rules-engine
  source:
    repoURL: git@github.com:dotcomrow/k8s-rules-engine.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: drools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true