apiVersion: v1
kind: Secret
metadata:
  name: zitadel
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-zitadel.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA+z+zgKFuc3oIr47rMgvFgRPy6WRQCSRfRFgdJKq87UgAAAKgjz6u9I8+r
    vQAAAAtzc2gtZWQyNTUxOQAAACA+z+zgKFuc3oIr47rMgvFgRPy6WRQCSRfRFgdJKq87Ug
    AAAEBbJUHC/EbivFABFYNDGu0qytcf5hkdFMGSbbdy0qiAzT7P7OAoW5zegivjusyC8WBE
    /LpZFAJJF9EWB0kqrztSAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: zitadel
  namespace: argocd
spec:
  description: Project for zitadel app
  sourceRepos:
    - '*'
  destinations:
    - namespace: zitadel
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
spec:
  project: zitadel
  source:
    repoURL: git@github.com:dotcomrow/k8s-zitadel.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true