apiVersion: v1
kind: Secret
metadata:
  name: kafka
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-kafka.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDcEudk5MiuuuChnksjsvb5rF9qhIYCSo8eUBINdQB7pQAAAKhdCvJEXQry
    RAAAAAtzc2gtZWQyNTUxOQAAACDcEudk5MiuuuChnksjsvb5rF9qhIYCSo8eUBINdQB7pQ
    AAAEAdi5z9EeWtr2GM1LeQ5aSrKQKddYhKonqn006DrccH7dwS52TkyK664KGeSyOy9vms
    X2qEhgJKjx5QEg11AHulAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kafka
  namespace: argocd
spec:
  description: Project for kafka app
  sourceRepos:
    - '*'
  destinations:
    - namespace: kafka
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: yugabyte
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: kafka
  source:
    repoURL: git@github.com:dotcomrow/k8s-kafka.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true