apiVersion: v1
kind: Secret
metadata:
  name: kyverno
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-kyverno.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCOivK36gtVkm43CVR7Jjqk/lui9fsi4OxBEv7HDtpyZAAAAKhUkPQTVJD0
    EwAAAAtzc2gtZWQyNTUxOQAAACCOivK36gtVkm43CVR7Jjqk/lui9fsi4OxBEv7HDtpyZA
    AAAEDgvaQgA6NYm92rUn6EyzT4EEo+gMSbeDFBpmOUcM377o6K8rfqC1WSbjcJVHsmOqT+
    W6L1+yLg7EES/scO2nJkAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kyverno
  namespace: argocd
spec:
  description: Project for Kyverno
  sourceRepos:
    - '*'
  destinations:
    - namespace: kyverno
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: kyverno
  source:
    repoURL: git@github.com:dotcomrow/k8s-kyverno.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true