apiVersion: v1
kind: Secret
metadata:
  name: logging-and-monitoring
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-grafana-metrics.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAh5niOmzrv+Q4qvqAihrx0Vg3oVeAzaBelIxqRdflQ+gAAAKjcgY6m3IGO
    pgAAAAtzc2gtZWQyNTUxOQAAACAh5niOmzrv+Q4qvqAihrx0Vg3oVeAzaBelIxqRdflQ+g
    AAAEClXdqFHLfVzMpZk92NUqUu6pVj+DbL9MOsdv7dCSzb2yHmeI6bOu/5Diq+oCKGvHRW
    DehV4DNoF6UjGpF1+VD6AAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: logging-and-monitoring
  namespace: argocd
spec:
  description: Project for logging and monitoring app
  sourceRepos:
    - '*'
  destinations:
    - namespace: logging-and-monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-and-monitoring
  namespace: argocd
spec:
  project: logging-and-monitoring
  source:
    repoURL: git@github.com:dotcomrow/k8s-grafana-metrics.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: logging-and-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true