apiVersion: v1
kind: Secret
metadata:
  name: repo-app1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  url: Z2l0QGdpdGh1Yi5jb206ZG90Y29tcm93L2s4cy1vbGxhbWEuZ2l0Cg==
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBqBNwGiIUJOh3setVYO53HK+aSjjfEY0Jm3Mn5D+9J+wAAAKhsmuChbJrg
    oQAAAAtzc2gtZWQyNTUxOQAAACBqBNwGiIUJOh3setVYO53HK+aSjjfEY0Jm3Mn5D+9J+w
    AAAEAYFHUyrjP0uLFxPueEXkdGWS+cH3SFFHGttZ93K3sJsWoE3AaIhQk6Hex61Vg7nccr
    5pKON8RjQmbcyfkP70n7AAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: dHJ1ZQ==
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ollama
  namespace: argocd
spec:
  description: Project for Ollama app
  sourceRepos:
    - '*'
  destinations:
    - namespace: ollama
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: ollama
  source:
    repoURL: git@github.com:dotcomrow/k8s-ollama.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
