apiVersion: v1
kind: Secret
metadata:
  name: repo-app1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
data:
  url: Z2l0QGdpdGh1Yi5jb206ZG90Y29tcm93L2s4cy1vbGxhbWEuZ2l0Cg==
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCcUJOd0dpSVVKT2gzc2V0VllPNTNISythU2pqZkVZMEptM01uNUQrOUord0FBQUtoc211Q2hiSnJnCm9RQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQnFCTndHaUlVSk9oM3NldFZZTzUzSEsrYVNqamZFWTBKbTNNbjVEKzlKK3cKQUFBRUFZRkhVeXJqUDB1TEZ4UHVlRVhrZEdXUytjSDNTRkZIR3R0WjkzSzNzSnNXb0UzQWFJaFFrNkhleDYxVmc3bmNjcgo1cEtPTjhSalFtYmN5ZmtQNzBuN0FBQUFIbUZrYldsdWFYTjBjbUYwYjNKQWMzVnVZMjloYzNRdWMzbHpkR1Z0Y3dFQ0F3ClFGQmdjPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  insecure: dHJ1ZQ==
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ollama
  namespace: argocd
spec:
  description: Project for Ollama app
  sourceRepos:
    - '*'
  destinations:
    - namespace: ollama
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: ollama
  source:
    repoURL: git@github.com:dotcomrow/k8s-ollama.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
