apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: patches
  namespace: argocd
spec:
  description: Project for Patches
  sourceRepos:
    - '*'
  destinations:
    - namespace: patches
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patches
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: patches
  source:
    repoURL: https://github.com/dotcomrow/k8s-core-patches.git
    targetRevision: prod
    path: nginx-ingress/overlays/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: apps
      kind: DaemonSet
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: batch
      kind: Job
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: batch
      kind: CronJob
      jqPathExpressions:
        - .spec.jobTemplate.spec.template.spec.containers[].resources
        - .spec.jobTemplate.spec.template.spec.initContainers[].resources

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m