apiVersion: v1
kind: Secret
metadata:
  name: patches
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-core-patches.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCXBlsdHDOjhLVtVEHSAf3SxEt7EkZCda8xUv2eLMJN+wAAAKg3Npe1NzaX
    tQAAAAtzc2gtZWQyNTUxOQAAACCXBlsdHDOjhLVtVEHSAf3SxEt7EkZCda8xUv2eLMJN+w
    AAAEDmVmKzopPwhplPz+3eBaav9khGHmewgvIhOFiMvGDgOZcGWx0cM6OEtW1UQdIB/dLE
    S3sSRkJ1rzFS/Z4swk37AAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: patches
  namespace: argocd
spec:
  description: Project for Patches
  sourceRepos:
    - '*'
  destinations:
    - namespace: patches
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patches
  namespace: argocd
spec:
  project: patches
  source:
    repoURL: git@github.com:dotcomrow/k8s-core-patches.git
    targetRevision: prod
    path: nginx-ingress/overlays/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true