apiVersion: v1
kind: Secret
metadata:
  name: pfsense-logging
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-pfsense-logging.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDOehRQ3tJ9j80dFiiz2xyxcCds2YSU8kU7gYxsbyvdrAAAAKhPd1fUT3dX
    1AAAAAtzc2gtZWQyNTUxOQAAACDOehRQ3tJ9j80dFiiz2xyxcCds2YSU8kU7gYxsbyvdrA
    AAAEDIdWiYk9UfPy1BujU/Xor2UMb48Wgsg7XftMH04tuNAs56FFDe0n2PzR0WKLPbHLFw
    J2zZhJTyRTuBjGxvK92sAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pfsense-logging
  namespace: argocd
spec:
  description: Project for pfSense logging
  sourceRepos:
    - '*'
  destinations:
    - namespace: pfsense-logging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfsense-logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/config-management-plugin: avp-v1
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: pfsense-logging
  source:
    repoURL: git@github.com:dotcomrow/k8s-pfsense-logging.git
    targetRevision: prod
    path: manifests
    plugin:
      name: avp-v1
  destination:
    server: https://kubernetes.default.svc
    namespace: pfsense-logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m