apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-redis.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDXz+SGj7UTPRAw5H2gi1Q67WzgU4gZeqmiDSDjNay4TgAAAKh2og22dqIN
    tgAAAAtzc2gtZWQyNTUxOQAAACDXz+SGj7UTPRAw5H2gi1Q67WzgU4gZeqmiDSDjNay4Tg
    AAAEDXxwfX71QHfTGpS3MIkd6I7Ee8C3yV1Y5f2cdjypjUXdfP5IaPtRM9EDDkfaCLVDrt
    bOBTiBl6qaINIOM1rLhOAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redis
  namespace: argocd
spec:
  description: Project for redis app
  sourceRepos:
    - '*'
  destinations:
    - namespace: redis
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: redis
  source:
    repoURL: git@github.com:dotcomrow/k8s-redis.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m