apiVersion: v1
kind: Secret
metadata:
  name: vault
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/k8s-vault.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBjLFrt8fd3zXQnRr+Ka5J3gQSasCGkJF/NrNCQnTVhpgAAAKhUpxeWVKcX
    lgAAAAtzc2gtZWQyNTUxOQAAACBjLFrt8fd3zXQnRr+Ka5J3gQSasCGkJF/NrNCQnTVhpg
    AAAECzmjfG5prUEJS4K4EobnJdtXyYdyG648NW0Tp/OdU+SGMsWu3x93fNdCdGv4prkneB
    BJqwIaQkX82s0JCdNWGmAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: argocd
spec:
  description: Project for Vault app
  sourceRepos:
    - '*'
  destinations:
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: vault
  source:
    repoURL: git@github.com:dotcomrow/k8s-vault.git
    targetRevision: prod
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true