apiVersion: v1
kind: Secret
metadata:
  name: yugabyte
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:dotcomrow/yugabyte-deployment.git
  sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACAcStcJF2yKQKp9d/jN+IiMViGoK+t65CMH4ukGIOsXsAAAAKil65KIpeuS
      iAAAAAtzc2gtZWQyNTUxOQAAACAcStcJF2yKQKp9d/jN+IiMViGoK+t65CMH4ukGIOsXsA
      AAAEAiXt4tHS85dek+uWzTZxNqkCmAHAnUKkc5GuQDE/6I8BxK1wkXbIpAqn13+M34iIxW
      Iagr63rkIwfi6QYg6xewAAAAHmFkbWluaXN0cmF0b3JAc3VuY29hc3Quc3lzdGVtcwECAw
      QFBgc=
      -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yugabyte
  namespace: argocd
spec:
  description: Project for Yugabyte
  sourceRepos:
    - '*'
  destinations:
    - namespace: yugabyte
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yugabyte
  namespace: argocd
  annotations:
    argocd.argoproj.io/config-management-plugin: avp-v1
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: yugabyte
  source:
    repoURL: git@github.com:dotcomrow/yugabyte-deployment.git
    targetRevision: prod
    path: manifests
    plugin:
      name: avp-v1
  destination:
    server: https://kubernetes.default.svc
    namespace: yugabyte
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m